ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/net_shr1234/helmcd'
  tag: 'chart_v1'

service:
  servicePort: 8080

probes:
  readiness: 
    - path: {{ .deployment.spec.template.spec.containers.readinessProbe.httpGet.path }}
    - initialDelaySeconds: {{ .deployment.spec.template.spec.containers.readinessProbe.initialDelaySeconds }}
    - timeoutSeconds:  {{ .deployment.spec.template.spec.containers.readinessProbe.timeoutSeconds }}
    - periodSeconds: {{ .deployment.spec.template.spec.containers.readinessProbe.periodSeconds }}
    - successThreshold: {{ .deployment.spec.template.spec.containers.readinessProbe.successThreshold }}
    - failureThreshold: {{ .deployment.spec.template.spec.containers.readinessProbe.failureThreshold }}
  liveness:
    - path: {{ .deployment.spec.template.spec.containers.livenessProbe.httpGet.path }}
    - initialDelaySeconds: {{ .deployment.spec.template.spec.containers.livenessProbe.initialDelaySeconds }}
    - timeoutSeconds:  {{ .deployment.spec.template.spec.containers.livenessProbe.timeoutSeconds }}
    - periodSeconds: {{ .deployment.spec.template.spec.containers.livenessProbe.periodSeconds }}
    - successThreshold: {{ .deployment.spec.template.spec.containers.livenessProbe.successThreshold }}
    - failureThreshold: {{ .deployment.spec.template.spec.containers.livenessProbe.failureThreshold }}

volume:
  muont: {{ .deployment.spec.template.spec.containers.volumeMounts.mountPath }}
